AWSTemplateFormatVersion: '2010-09-09'

Description: >
  CloudFormation template for a highly available web infrastructure
  with VPC, public and private subnets, EC2 instances and ALB.

Resources:

  WebVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: cfn-web-vpc

      PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-south-1a
      Tags:
        - Key: Name
          Value: cfn-public-subnet-a

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-south-1b
      Tags:
        - Key: Name
          Value: cfn-public-subnet-b

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: ap-south-1a
      Tags:
        - Key: Name
          Value: cfn-private-subnet-a

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.12.0/24
      AvailabilityZone: ap-south-1b
      Tags:
        - Key: Name
          Value: cfn-private-subnet-b
      
